name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Copy files to Nginx
        run: |
          sudo apt-get update
          sudo apt-get install -y nginx
          sudo rm -rf /var/www/html/*
          sudo cp -r build/* /var/www/html/
          sudo systemctl restart nginx
