name: Push-to-server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Install PM2
        run: npm install -g pm2

      - name: Start or Restart MYAPP
        run: |
          pm2 start build/server.js --name MYAPP || pm2 restart MYAPP
